repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types:
        - python
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
        - python
    -   id: isort
        name: isort
        entry: isort
        language: system
        types:
        - python
    -   id: bandit
        name: bandit
        entry: bandit --ini .bandit
        language: system
        types:
        - python
    -   id: black
        name: black
        entry: black
        language: system
        types:
        - python
