repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff_format
        name: ruff_format
        entry: ruff format .
        language: system
        types:
          - python
      - id: ruff_lint
        name: ruff_lint
        entry: ruff check . --fix --exit-non-zero-on-fix
        language: system
        types:
          - python
