name: Release

on:
  release:
    types: [released]

jobs:
  package_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: python -m pip install -U pip setuptools wheel twine

      - name: install poetry and poetry-dynamic-versioning
        run: python -m pip install -U poetry poetry-dynamic-versioning

      - name: building package
        run: poetry build

      - name: Upload packages
        run: "python -m twine upload dist/*"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
